
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CompteService", targetNamespace = "http://JAXWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompteService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod(operationName = "ListeComptes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListeComptes", targetNamespace = "http://JAXWS/", className = "proxy.ListeComptes")
    @ResponseWrapper(localName = "ListeComptesResponse", targetNamespace = "http://JAXWS/", className = "proxy.ListeComptesResponse")
    @Action(input = "http://JAXWS/CompteService/ListeComptesRequest", output = "http://JAXWS/CompteService/ListeComptesResponse")
    public List<Compte> listeComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://JAXWS/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://JAXWS/", className = "proxy.GetCompteResponse")
    @Action(input = "http://JAXWS/CompteService/getCompteRequest", output = "http://JAXWS/CompteService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://JAXWS/", className = "proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://JAXWS/", className = "proxy.ConvertResponse")
    @Action(input = "http://JAXWS/CompteService/ConvertRequest", output = "http://JAXWS/CompteService/ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
